//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.20 at 01:10:31 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com/petzila/api/model")
package com.petzila.api.model;
