//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.17 at 11:31:36 AM CST 
//


package com.petzila.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XPetAge.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="XPetAge">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="zero-three"/>
 *     &lt;enumeration value="three-five"/>
 *     &lt;enumeration value="five-ten"/>
 *     &lt;enumeration value="ten-fifthteen"/>
 *     &lt;enumeration value="fifthteen-more"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "XPetAge")
@XmlEnum
public enum XPetAge {

    @XmlEnumValue("zero-three")
    ZERO_THREE("zero-three"),
    @XmlEnumValue("three-five")
    THREE_FIVE("three-five"),
    @XmlEnumValue("five-ten")
    FIVE_TEN("five-ten"),
    @XmlEnumValue("ten-fifthteen")
    TEN_FIFTHTEEN("ten-fifthteen"),
    @XmlEnumValue("fifthteen-more")
    FIFTHTEEN_MORE("fifthteen-more");
    private final String value;

    XPetAge(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XPetAge fromValue(String v) {
        for (XPetAge c: XPetAge.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
