//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.20 at 01:10:31 PM CST 
//


package com.petzila.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profilePicture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resourceType" type="{urn:com/petzila/api/model}XResourceType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{urn:com/petzila/api/model}XName"/>
 *         &lt;element name="location" type="{urn:com/petzila/api/model}XLocation"/>
 *         &lt;element name="signupType" type="{urn:com/petzila/api/model}XSignUpType"/>
 *         &lt;element name="socialNetworkID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facebookToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facebookTokenType" type="{urn:com/petzila/api/model}XFacebookTokenType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "email",
    "password",
    "username",
    "profilePicture",
    "resourceType",
    "description",
    "name",
    "location",
    "signupType",
    "socialNetworkID",
    "facebookToken",
    "facebookTokenType"
})
@XmlRootElement(name = "XSignUp")
public class XSignUp {

    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String profilePicture;
    @XmlElement(required = true)
    protected XResourceType resourceType;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected XName name;
    @XmlElement(required = true)
    protected XLocation location;
    @XmlElement(required = true)
    protected XSignUpType signupType;
    @XmlElement(required = true)
    protected String socialNetworkID;
    @XmlElement(required = true)
    protected String facebookToken;
    @XmlElement(required = true)
    protected XFacebookTokenType facebookTokenType;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the profilePicture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfilePicture() {
        return profilePicture;
    }

    /**
     * Sets the value of the profilePicture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfilePicture(String value) {
        this.profilePicture = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link XResourceType }
     *     
     */
    public XResourceType getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XResourceType }
     *     
     */
    public void setResourceType(XResourceType value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link XName }
     *     
     */
    public XName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link XName }
     *     
     */
    public void setName(XName value) {
        this.name = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link XLocation }
     *     
     */
    public XLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link XLocation }
     *     
     */
    public void setLocation(XLocation value) {
        this.location = value;
    }

    /**
     * Gets the value of the signupType property.
     * 
     * @return
     *     possible object is
     *     {@link XSignUpType }
     *     
     */
    @Deprecated
    public XSignUpType getSignupType() {
        return signupType;
    }

    /**
     * Sets the value of the signupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XSignUpType }
     *     
     */
    public void setSignupType(XSignUpType value) {
        this.signupType = value;
    }

    /**
     * Gets the value of the socialNetworkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialNetworkID() {
        return socialNetworkID;
    }

    /**
     * Sets the value of the socialNetworkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialNetworkID(String value) {
        this.socialNetworkID = value;
    }

    /**
     * Gets the value of the facebookToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacebookToken() {
        return facebookToken;
    }

    /**
     * Sets the value of the facebookToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacebookToken(String value) {
        this.facebookToken = value;
    }

    /**
     * Gets the value of the facebookTokenType property.
     * 
     * @return
     *     possible object is
     *     {@link XFacebookTokenType }
     *     
     */
    public XFacebookTokenType getFacebookTokenType() {
        return facebookTokenType;
    }

    /**
     * Sets the value of the facebookTokenType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XFacebookTokenType }
     *     
     */
    public void setFacebookTokenType(XFacebookTokenType value) {
        this.facebookTokenType = value;
    }

}
